### ISSUE TITLE
poetry install does not work

### ISSUE THREAD

**Issue by libialany** [osl-incubator/makim#1]
* makim version: latest
* Python version: Python 3.10.6
* Operating System: Ubuntu 22.04.1

### Description

I tried to install with poetry install.
The makim command is not found and also no response comes out if i run python makim/makim.py

### What I Did

```
poetry install
```

**Comment by xmnlab** [comment]
hi @libialany thanks for opening this issue.
I will update the contributing guide soon if all this information.

we use conda as an environment tool. it is not mandatory .. but it would allow you to have a way to create easily a virtual environment locally. also, in same cases, we need some system dependency that can be also be installed inside conda. it is really a great tool.

so, if you don't have it yet, you can download mamba-forge (miniconda + conda-forge + mamba), it is a nice way to have all in one.

here is the link: https://github.com/conda-forge/miniforge#mambaforge

after you have mamba forge installed and working (probably you need to restart your terminal session) you can create a new environment. In the root path of the project:

```bash
mamba env create --file conda/dev.yaml
```

next, you need to activate the environment:

```bash
conda activate makim
```

now poetry should be available for you :)

I am updating the contributing guide and I will publish the documentation soon.

I am closing this issue. but feel free to reopen that if that doesn't work ... also, if you have more question about this issue, feel free to ask it here :)

thanks

**Comment by xmnlab** [comment]
@libialany I just merged a PR. now the tools should be more stable.
new features are coming during this week, such as support for "arguments".
and maybe next week I will add support for conditionals "if"

thanks for playing with makim :)
