### ISSUE TITLE
Update package metadata in pyproject

### ISSUE THREAD

**Issue by esloch** [osl-incubator/makim#3]
Add a small description about the package and add link to the GitHub repository.

**Comment by xmnlab** [comment]
the pypi page doesn't show much information about the project: https://pypi.org/project/makim/

it would be nice to have something like this: https://pypi.org/project/epigraphhub/

The file to be updated is: https://github.com/osl-incubator/makim/blob/main/pyproject.toml
and this is an example: https://github.com/thegraphnetwork/epigraphhub_py/blob/main/pyproject.toml

**Comment by git-devansh** [comment]
Can i work on this?

**Comment by xmnlab** [comment]
That would be great! Please go ahead! <3

**Comment by git-devansh** [comment]
https://github.com/osl-incubator/makim/pull/29 

This can work?

**Comment by xmnlab** [comment]
Thank you @git-devansh
