### ISSUE TITLE
Recommend the most probable command when a command (target) doesn't exist

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#36]
When the user call a makim target that doesn't exist, it would be nice to have some mechanism that will 
proposal some alternative using something like a fuzzy search

**Comment by xmnlab** [comment]
This is a generic example from chatgpt (it was not tested):

```python

import argparse
from fuzzywuzzy import process

parser = argparse.ArgumentParser(prog='makim')
subparsers = parser.add_subparsers()

parser_a = subparsers.add_parser('add')
parser_a.add_argument('item', help='item to add')

parser_l = subparsers.add_parser('list')
parser_l.add_argument('--all', action='store_true', help='list all items')

args = parser.parse_args()

# Check if sub-command is valid
try:
    sub_command = args.sub_command
except AttributeError:
    parser.print_help()
    exit()

valid_commands = ['add', 'list']
if sub_command not in valid_commands:
    # Suggest alternative sub-command
    best_match = process.extractOne(sub_command, valid_commands)[0]
    print(f"Invalid command '{sub_command}'. Did you mean '{best_match}'?")
    exit()

# Execute the sub-command
if sub_command == 'add':
    print(f"Adding item '{args.item}'")
elif sub_command == 'list':
    if args.all:
        print("Listing all items")
    else:
        print("Listing items")

```

**Comment by abhijeetSaroha** [comment]
Hey @xmnlab , After conducting an investigation into the issue, I have determined that, with the transition to Typer and its dynamic implementation, suggesting the most probable command may not be feasible. The error arising from an incorrect target command is inherent to Typer's dynamic nature and is not originating from the Makim core file.

Therefore, it appears that providing suggestions for the most probable command may not be possible.

**Comment by xmnlab** [comment]
@abhijeetSaroha , using chat gpt, I found the following alternative, could you check if that would work?

As of my last update in April 2023, Typer, a library for building command-line interface (CLI) applications in Python, does not natively support automatic recommendations for similar commands if a command is not found. Typer is built on top of Click, which also doesn't provide this feature out of the box. However, you can implement a custom solution to achieve similar functionality.

Here's a basic approach to implement command suggestions in Typer:

1. **Capture Unrecognized Commands**: Override the default behavior when an unrecognized command is entered. You'll need to catch the exception related to unknown commands.

2. **Implement a Suggestion Mechanism**: Create a function that suggests the closest match to the entered command from the list of available commands. This can be done using algorithms like Levenshtein distance (for string similarity).

3. **Display the Suggestion**: When an unrecognized command is entered, display the suggestion to the user.

Here is an example implementation:

```python
import typer
from typing import Optional
from Levenshtein import distance  # You might need to install the 'python-Levenshtein' package

app = typer.Typer()

def suggest_command(user_input: str, available_commands: list) -> Optional[str]:
    """
    Suggest the closest command to the user input based on Levenshtein distance.

    Parameters:
    user_input (str): The command input by the user.
    available_commands (list): A list of available commands.

    Returns:
    Optional[str]: The suggested command if a close match is found, else None.
    """
    closest_match = None
    closest_dist = float('inf')
    for command in available_commands:
        dist = distance(user_input, command)
        if dist < closest_dist:
            closest_match = command
            closest_dist = dist
    return closest_match if closest_dist < len(user_input) // 2 else None

@app.callback()
def main(ctx: typer.Context):
    ctx.obj = {"commands": app.registered_commands}

@app.command()
def foo():
    typer.echo("Running Foo")

@app.command()
def bar():
    typer.echo("Running Bar")

if __name__ == "__main__":
    try:
        app()
    except typer.exceptions.NoSuchCommand as e:
        available_cmds = [cmd.name for cmd in app.registered_commands]
        suggestion = suggest_command(e.name, available_cmds)
        if suggestion:
            typer.secho(f"Command '{e.name}' not found. Did you mean '{suggestion}'?", fg=typer.colors.RED)
        else:
            typer.secho(f"Command '{e.name}' not found.", fg=typer.colors.RED)
```

In this implementation:

- The `suggest_command` function calculates the Levenshtein distance between the user's input and the available commands to find the closest match.
- If an unrecognized command is entered, the catch block suggests the closest match.
- The Levenshtein distance calculation is a simple way to find string similarity. The threshold for suggestions (`len(user_input) // 2`) can be adjusted based on your needs.

### Note:

- You'll need to install the `python-Levenshtein` package for string similarity calculations (`pip install python-Levenshtein`).
- This implementation is a basic example. Depending on the complexity and structure of your CLI application, you might need to adapt or extend this approach.

**Comment by xmnlab** [comment]
and maybe it would be better to use also fuzzy search as well:

Yes, using a fuzzy search algorithm could indeed be a more effective approach for suggesting similar commands in a Typer application, compared to strictly using the Levenshtein distance. Fuzzy search algorithms are designed to find matches that are "close" to a given target string, even if they're not exact, which can be more user-friendly for command line suggestions.

One popular choice for implementing fuzzy search in Python is the `fuzzywuzzy` library, which also uses Levenshtein distance internally but provides a higher-level API that's well-suited for tasks like command suggestions.

Here's how you could modify the previous example to use `fuzzywuzzy` for command suggestions:

First, install `fuzzywuzzy`:

```bash
pip install fuzzywuzzy
```

Then, update the script:

```python
import typer
from fuzzywuzzy import process  # Import the fuzzywuzzy process module

app = typer.Typer()

def suggest_command(user_input: str, available_commands: list) -> str:
    """
    Suggest the closest command to the user input using fuzzy search.

    Parameters:
    user_input (str): The command input by the user.
    available_commands (list): A list of available commands.

    Returns:
    str: The suggested command.
    """
    suggestion, _ = process.extractOne(user_input, available_commands)
    return suggestion

@app.callback()
def main(ctx: typer.Context):
    ctx.obj = {"commands": app.registered_commands}

@app.command()
def foo():
    typer.echo("Running Foo")

@app.command()
def bar():
    typer.echo("Running Bar")

if __name__ == "__main__":
    try:
        app()
    except typer.exceptions.NoSuchCommand as e:
        available_cmds = [cmd.name for cmd in app.registered_commands]
        suggestion = suggest_command(e.name, available_cmds)
        typer.secho(f"Command '{e.name}' not found. Did you mean '{suggestion}'?", fg=typer.colors.RED)
```

In this implementation, `fuzzywuzzy.process.extractOne` is used to find the command that is closest to the user's input. This method returns the best match along with its similarity score. The function `suggest_command` then returns the suggested command name.

### Benefits of Using `fuzzywuzzy`:

- **Higher Level API**: `fuzzywuzzy` simplifies the process of finding the best match out of a list of choices.
- **Customizable**: You can adjust the criteria for matching (e.g., setting a minimum similarity threshold).
- **User-Friendly**: It often provides more intuitive suggestions compared to raw Levenshtein distance calculations.

### Note:

- `fuzzywuzzy` uses Levenshtein distance internally but offers a more user-friendly and flexible way to implement fuzzy matching.
- As always, it's important to test the implementation thoroughly to ensure that it behaves as expected in different scenarios.

**Comment by abhijeetSaroha** [comment]
That's a great idea; I gave it a shot to see if catching the error could do the trick. However, I've been at it for quite a while, and it seems the error is Typer-specific (my thought). It's not your typical Python error, and it's nowhere to be found in the Typer docs.

Any insights or alternative suggestions would be much appreciated!

The error looks like this:
![image](https://github.com/osl-incubator/makim/assets/108522472/cb56089f-538a-418c-a7b9-41f716391a42)

**Comment by xmnlab** [comment]
you can try with something like:

```
try:
    .... # the code
except Exception as e:
    breakpoint()
```

and check the type of `e`

**Comment by abhijeetSaroha** [comment]
> ```
> try:
>     .... # the code
> except Exception as e:
>     breakpoint()
> ```

I have tried this before, but codebase don't enter in except block for `Exception`, or other types of error except for `SystemExit` and for systemexit it prints 2 as `e`.

**Comment by xmnlab** [comment]
great. could it be 1h later? I have an agenda conflict at that time

**Comment by xmnlab** [comment]
done
