### ISSUE TITLE
Add function when press TAB key 

### ISSUE THREAD

**Issue by esloch** [osl-incubator/makim#4]
### Description

Add function to view all yaml file targets in the console after entering the Makim command followed from the <tab> key.

### What I Did

```
makim <TAB>
```

Read about the [argcomplete](https://pypi.org/project/argcomplete/) library.

**Comment by xmnlab** [comment]
maybe something to be used: https://kislyuk.github.io/argcomplete/

**Comment by xmnlab** [comment]
move from argparse to typer

**Comment by xmnlab** [comment]
another option would be implement that manually

**Comment by xmnlab** [comment]
resolved by #82
